language: node_js
cache:
  directories:
  - $HOME/.yarn-cache
  - $HOME/google-cloud-sdk
env:
  global:
  - CLOUDSDK_CORE_DISABLE_PROMPTS=1
  - GOOGLE_APPLICATION_CREDENTIALS=$TRAVIS_BUILD_DIR/client-secret.json
  - GCP_PROJECT_ID=unpkg-gcp
  - GCP_ZONE=us-central1-a
  - CLUSTER_NAME=cluster-1
  - TAG=${TRAVIS_COMMIT::8}
services:
- redis-server
- docker
before_install:
- if [ ! -d $HOME/google-cloud-sdk/bin ]; then
    rm -rf $HOME/google-cloud-sdk;
    curl https://sdk.cloud.google.com | bash > /dev/null;
  fi
- source $HOME/google-cloud-sdk/path.bash.inc
- gcloud components update kubectl
- gcloud version
script:
- yarn test --silent --maxWorkers=4
- yarn build
# - docker build -t "gcr.io/$GCP_PROJECT_ID/server:$TAG" -f Dockerfile.server .
# - docker build -t "gcr.io/$GCP_PROJECT_ID/worker:$TAG" -f Dockerfile.worker .
- docker images
# before_deploy:
# - openssl aes-256-cbc -K $encrypted_f0cc5a0bf9b1_key -iv $encrypted_f0cc5a0bf9b1_iv
#   -in client-secret.json.enc -out $GOOGLE_APPLICATION_CREDENTIALS -d
# - gcloud auth activate-service-account --key-file $GOOGLE_APPLICATION_CREDENTIALS
# - gcloud auth configure-docker
# - gcloud config set project $GCP_PROJECT_ID
# - gcloud config set compute/zone $GCP_ZONE
# - gcloud container clusters get-credentials $CLUSTER_NAME
# - kubectl version
deploy:
- provider: heroku
  skip_cleanup: true
  app: unpkg
  api_key:
    secure: qJTOiZE1hbghS0U7xpqU/38jm1Dga8bycsgDTW2wOSfAxqxtR4rAilW3ffBHY8/VSqt5GLkyPqFzb9R3I+xlcK6oakQyNMFGjQwMAqwdtHjucr45jWYNeqWf6Nbrrj+0LiQiH/uqMB4mKPquGqx2k2JIHW6jy5ndK14lI9a7SP44edyNugjhNW+OOYjwqo6maHvRoFNxL7kxrw7Js90d0gIKXpunBqHmxmr/hlYcGr9qJ+bLUXxmObxpoFWKHE0iTsTw3C3y558wZpHTfa3vXIvhseW2q7ATuRRVBv8StNjYxYSGpeZA+59d48z3EPK/mp7ybZO6cWyaBdcA9yF3thISEXlXcRcCck5KYk4gwzgrcfug59Z1VJUVXCywJTUu42V5ISoyUKJ+DelkkvMpXQH9T9fxm5eWEwb7sb+UTo3R8mlFliBogvXrWOKNXeRFsLQXH3/YmOUWONUUYRJS11K/p+sFOTfTfaH5lS0AFKCAKtvfLjdLUclsmmrITSFQa42/SRsFx88v3RxDL93r2838p51N7U/RqOqTNfQ8JR2iQOWlthMEvnVZMNs3VT9lW5eYIdTd5kpW/ARVtQf2drVVYR5BzNRJlGyw7M4x1riwNO7XhNqH76Iy/zMbeEDGaXqBCfzgq9vsRAjZm/TFKw8eOEy8+EGxLrBKD1U7EuI=
  on:
    branch: master
- provider: script
  # script: docker push "gcr.io/$GCP_PROJECT_ID/server:$TAG" && docker push "gcr.io/$GCP_PROJECT_ID/worker:$TAG"
  script:
  - |
    openssl aes-256-cbc -K $encrypted_f0cc5a0bf9b1_key -iv $encrypted_f0cc5a0bf9b1_iv -in client-secret.json.enc -out $GOOGLE_APPLICATION_CREDENTIALS -d;
    gcloud auth activate-service-account --key-file $GOOGLE_APPLICATION_CREDENTIALS;
    gcloud auth configure-docker;
    gcloud config set project $GCP_PROJECT_ID;
    gcloud config set compute/zone $GCP_ZONE;
    gcloud container clusters get-credentials $CLUSTER_NAME;
    kubectl version;
  on:
    branch: gke
